all:
  hosts:
    R1:
      ansible_host: 10.10.1.1
    SW1:
      ansible_host: 10.10.1.2
    ASA1:
      ansible_host: 10.10.1.3
    FTD1:
      ansible_host: 10.10.1.4
    PA1:
      ansible_host: 10.10.1.5
