---
- name: Gather comprehensive ASA facts
  asa_facts:
    gather_subset:
      - all
  register: asa_device_facts

- name: Set ASA device facts
  set_fact:
    hostname: "{{ ansible_net_hostname }}"
    model: "{{ ansible_net_model }}"
    ios_type: "asa"
    serial: "{{ ansible_net_serialnum }}"
    current_ver: "{{ ansible_net_version }}"
    device_mode: "asa"
    interfaces: "{{ ansible_net_interfaces }}"
    device_type: "asa"